Milestone5 - Even handler and refactor code
janis-jenny/Calculator pull request #4
Opened 2021-08-06 21:46 UTC by janis-jenny

- Add logic for numbers  in the handleClick listener on the App component
- Add logic for operations  in the handleClick listener on the App component
-  Refactor calculate method and operate 
-  Refactor render method on the App component

2021-08-06 22:10 UTC, rukundoeric requested changes
Hi @janis-jenny , 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-06 22:10 UTC, rukundoeric commented on src/components/App.js
> +    }
- [x] <b>REQUIRED:</b> As it is stated in project specifications, all calculations operations should be done in calculate function from `logic/calculate.js` file. Kindly   Move this code to calculate function. The content of `handlClick` function should be something like this...
```Javascript
  handleClick = (buttonName) => {
     this.setState(calculate(this.state, buttonName));
  }
```

2021-08-06 22:10 UTC, rukundoeric commented on src/logic/operate.js
> +  console.log('b', b);
- [ ] <b>REQUIRED:</b> Make sure to always keep your code clean by making sure that you delete all debugging codes(console logs) when you no longer need them.

2021-08-06 22:10 UTC, rukundoeric commented on src/logic/operate.js
> +/* eslint-disable no-console */
- [ ] <b>REQUIRED:</b> This comment is no longer necessary here and besides, you are not allowed to use `eslint-disable` unless of course when it is totally obvious that there is no other way. kindly remove it.

2021-08-07 03:52 UTC, rindrajosia requested changes
Hi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-07 03:52 UTC, rindrajosia commented on src/logic/calculate.js
> +    }
- [ ] [REQUIRED] I cannot perform any operation with these operators. Please fix it.
![1](https://user-images.githubusercontent.com/58552748/128587036-ed268ccd-1462-419f-893b-a374e30da77b.gif)

2021-08-07 04:35 UTC, rukundoeric approved these changes
Hi @janis-jenny,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Kindly make sure to fix broken screenshots from your README before you merge this PR.


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-07 04:35 UTC, rukundoeric commented on src/logic/calculate.js
>    }
- [ ] <b>OPTIONAL:</b> There is no need to use `if condition` and `switch case` separately in this function, you can simply move these conditions in the switch case below.

2021-08-08 01:10 UTC, merged